M48
; DRILL file {KiCad (6.0.4)} date Wed Feb  1 13:33:50 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-01T13:33:50+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X2.0614Y-2.1965
X2.0614Y-3.2898
X2.7307Y-2.1965
X2.7307Y-3.2898
T0
M30
